### ISSUE TITLE
Re-design the architecture of modifier specs

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nkeymaps#12]
For context, follow the threads in #9 and #10. 

-----

After plenty of discussion I have a suggestion that will requires minimal changes and maximizes results.

Release a new version (so that we can break backwards compatibility) featuring the changes below.

### Drop `name` slot in `modifier`

```lisp
(defstruct modifier
  (system-name "" :type string)
  (shortcut "" :type string)) 
```

The slot `name` doesn't give us much. I don't think anyone will miss specifying a keyspec as `"control-a"`.

Note that this change would require a minor refactor of `translate-modifiers` at `nyxt/source/renderer/gtk.lisp`.

### Refactor `*print-shortcut*`

Rename it to `*modifier-shortcut-p*`. When `t` the keyspec can be specified à la Emacs (e.g. `"C-a"`). Otherwise, use the common-place representation (e.g. `"Ctrl-a"`).

The default value should be `nil` since Nyxt uses the cua keyscheme by default.

**Comment by Ambrevar** [comment]
I think this is shortsighted: it will _force_ for unportable code.  A big no-no in my opinion.

I think #11 is a mistake, see https://github.com/atlas-engineer/nkeymaps/pull/11#issuecomment-1623186475.

So quite the opposite: I opt for reverting #11, keeping `name` and `shortcut` as they allow for _portable_ code.

**Comment by Ambrevar** [comment]
> A decision has been made already, so let's not move in circles.

I was not part of the decision to merge #11.  

We are also not moving in circles,  it's perfectly fine, I believe, to keep discussing in issues and pull requests before merging too hastily.

Let's revert and keep discussing the issue.  It may very well be that we're not going to move forward from #11 but take a different route instead.
