### ISSUE TITLE
Impossible to use typed modifiers in `make-key`?

### ISSUE THREAD

**Issue by simendsjo** [atlas-engineer/nkeymaps#20]
`make-key` requires a `list` for `:modifiers`. The modifiers are sent to `modspecs->modifiers` which requires `(or (list-of string) fset:wb-set)`. This means I cannot send e.g. `nkeymaps:+control+` either as a list or as an `fset:set`, but have to extract its `string` or `shortcut` as a list. Maybe `(or (list-of string) (list-of modifier))` would be a better API?

**Comment by Ambrevar** [comment]
I'm on it.

**Comment by Ambrevar** [comment]
Does #20 cut it for you?

**Comment by simendsjo** [comment]
Yes, that works and simplifies the API for me at least. Thanks!
